### ISSUE TITLE
Failed to parse locationId for SUPL version 2.0

### ISSUE THREAD

**Issue by AndreySV** [Eierkopp/supl-hack#1]
supl-proxy is run as 
```
 /usr/lib/supl-proxy/venv/bin/python3 /usr/bin/supl-proxy.py -g /usr/share/supl-proxy/asn1 -l /var/log/supl-proxy/supl-proxy.log -s supl.google.com:7276 -v -p 7279
```

When A-GNSS data is requested by a phone log file contains following messages
```
 ...
  "message": [
    "msSUPLSTART",
    {
      "sETCapabilities": {
        "posTechnology": {
          "agpsSETassisted": false,
          "agpsSETBased": true,
          "autonomousGPS": true,
          "aFLT": false,
          "eCID": true,
          "eOTD": false,
          "oTDOA": false
        },
        "prefMethod": "noPreference",
        "posProtocol": {
          "tia801": false,
          "rrlp": false,
          "rrc": false
        }
      },
      "locationId": {
        "cellInfo": [
          null,
          null
        ],
        "status": "current"
      },
      "qoP": {
        "horacc": 19,
        "maxLocAge": 0,
        "delay": 5
      }
    }
  ]
}
2024-10-27 19:31:16,423 [ERROR] asyncio: Task exception was never retrieved
future: <Task finished name='Task-8' coro=<handle_connection() done, defined at /usr/bin/supl-proxy.py:110> exception=EncodeError('Expected data of type tuple(str, object), but got (None, None).')>
Traceback (most recent call last):
  File "/usr/bin/supl-proxy.py", line 137, in handle_connection
    orig_imsi = await forward_packet(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/supl-proxy.py", line 104, in forward_packet
    data = supl_db.encode("ULP-PDU", pdu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/compiler.py", line 137, in encode
    type_.check_types(data)
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/compiler.py", line 102, in check_types
    return self.type_checker.encode(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 311, in encode
    raise e
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 307, in encode
    self._type.encode(data)
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 142, in encode
    self.encode_members(data)
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 154, in encode_members
    raise e
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 150, in encode_members
    member.encode(data[name])
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 247, in encode
    raise e
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 243, in encode
    member.encode(data[1])
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 142, in encode
    self.encode_members(data)
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 154, in encode_members
    raise e
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 150, in encode_members
    member.encode(data[name])
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 142, in encode
    self.encode_members(data)
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 154, in encode_members
    raise e
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 150, in encode_members
    member.encode(data[name])
  File "/usr/lib/supl-proxy/venv/lib/python3.11/site-packages/asn1tools/codecs/type_checker.py", line 224, in encode
    raise EncodeError(
asn1tools.codecs.EncodeError: ULP-PDU.message.msSUPLSTART.locationId.cellInfo: Expected data of type tuple(str, object), but got (None, None).

```
CellInfo in locationId is null, but  if the request is parseed with a different parser, than all data are correctly parsed.
```
            <locationId>
                <cellInfo>
                    <ver2-CellInfo-extension>
                        <lteCell>
                            <cellGlobalIdEUTRA>
                                <plmn-Identity>
                                    <mcc>
                                        <MCC-MNC-Digit>2</MCC-MNC-Digit>
                                        <MCC-MNC-Digit>5</MCC-MNC-Digit>
                                        <MCC-MNC-Digit>0</MCC-MNC-Digit>
                                    </mcc>
                                    <mnc>
                                        <MCC-MNC-Digit>2</MCC-MNC-Digit>
                                        <MCC-MNC-Digit>0</MCC-MNC-Digit>
                                    </mnc>
                                </plmn-Identity>
                                <cellIdentity>
                                    1011111011001010001100010101
                                </cellIdentity>
                            </cellGlobalIdEUTRA>
                            <physCellId>461</physCellId>
                            <trackingAreaCode>
                                0100110100001101
                            </trackingAreaCode>
                            <rsrpResult>31</rsrpResult>
                            <rsrqResult>16</rsrqResult>
                            <tA>8</tA>
                        </lteCell>
                    </ver2-CellInfo-extension>
                </cellInfo>
                <status><current/></status>
            </locationId>
```

**Comment by Eierkopp** [comment]
Many thanks for your report. The problem seems to be, that your phone sends SUPL V2 requests, while supl_proxy only knows about SUPL V1, i.e. the ASN.1 grammar is pulled off the spec `OMA-TS-ULP-V1_0-20070615-A.pdf`. 

Unfortunately I haven't got access to a device that produces SUPL V2 traffic. It would be nice, if you could send me the captured (e.g. with wireshark) raw unencrypted TCP data of a SUPL request by your phone. With a bit of luck only the ANS.1 grammar files need to be replaced by the content of [the V2 spec](https://www.openmobilealliance.org/release/SUPL/V2_0_6-20200804-A/OMA-TS-ULP-V2_0_6-20200804-A.pdf).

**Comment by AndreySV** [comment]
I've sent you dump from my device to your e-mail.

**Comment by Eierkopp** [comment]
I've updated the ULP spec to V2. Using that spec, the proxy could decode and forward the request. V1 still seems to work as well. No idea how to better decode `lPPPayload`, though. Could you please give it a try and produce another trace in case something still breaks?

Edit: lPPPayload is now understood

**Comment by AndreySV** [comment]
Thanks, I've tested last changes and confirm that V2 requests are working now. Phone gets data from the proxy and sees the sky immediately after response.
